version: '2'

services:
  test:
    image: node
    container_name: gascalc
    depends_on:
      - localgeth
    volumes:
      - ..:/app
    working_dir: /app
    restart: "no"
    environment:
      - HARDHAT_NETWORK=localgeth
    command: "yarn mocha-gascalc"

  #configuration is a copy of github/.workflows/build.xml
  localgeth:
    image: ethereum/client-go:release-1.10
    container_name: localgeth
    command: >-
      --verbosity 1
      --http.vhosts '*,localhost,host.docker.internal'
      --http
      --http.api personal,eth,net,web3,debug
      --http.corsdomain '*'
      --http.addr "0.0.0.0"
      --nodiscover --maxpeers 0 --mine
      --networkid 1337
      --dev
      --allow-insecure-unlock
      --rpc.allow-unprotected-txs
      --dev.gaslimit 20000000
