name: Build
on: push

env:
  TS_NODE_TRANSPILE_ONLY: 1
  FORCE_COLORS: 1

# todo: extract shared seto/checkout/install/compile, instead of repeat in each job.
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - uses: actions/cache@v3
        id: hardhat-cache
        with:
          path: |
            artifacts
            contracts/types
          key: ${{ runner.os }}-${{ hashFiles('contracts/**/*.sol') }}
      - name: Compile
        if: steps.hardhat-cache.outputs.cache-hit != 'true'
        run: yarn compile

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: [setup, lint]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn run ci

  gas-checks:
    runs-on: ubuntu-latest
    needs: setup
    services:
      localgeth:
        image: dtr22/geth-dev

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: |
            artifacts
            contracts/types
          key: ${{ runner.os }}-${{ hashFiles('contracts/**/*.sol') }}
      - run: yarn ci-gas-calc

  coverage:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: |
            artifacts
            contracts/types
          key: ${{ runner.os }}-${{ hashFiles('contracts/**/*.sol') }}
      - run: FORCE_COLOR=1 yarn coverage
      - uses: actions/upload-artifact@v3
        with:
          name: solidity-coverage
          path: |
            coverage/
            coverage.json
